-- 1.1). Creación de la tabla TB_PRODUCTOS_PABLO

CREATE TABLE tb_productos_pablo (
	id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	comercial_name VARCHAR2(100) NOT NULL,
	category  VARCHAR2(50) NOT NULL,
	price NUMBER(8,2) DEFAULT 0 NOT NULL,
	stock NUMBER(8,0) DEFAULT 0 NOT NULL,
	fecha_alta DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
	web_status VARCHAR2(8) DEFAULT 'activo' NOT NULL,
	sku VARCHAR2(20) UNIQUE NOT NULL,
	inserted_by VARCHAR2(128) DEFAULT USER NOT NULL,
	tax NUMBER(3,2) DEFAULT 0.21,
	-- Constraints
	CONSTRAINT ck_tb_productos_pablo_price_notlessthanzero CHECK (price >= 0),
	CONSTRAINT ck_tb_productos_pablo_web_status_enum CHECK (web_status IN('activo','inactivo'))
);

SELECT * FROM  tb_productos_pablo;
-- 1.2) Renombrar SKU → CODIGO_SKU

ALTER TABLE tb_productos_pablo RENAME COLUMN sku TO CODIGO_SKU;

SELECT * FROM  tb_productos_pablo;

-- 1.3) Ampliar el tamaño de comercial_name

ALTER TABLE tb_productos_pablo MODIFY comercial_name VARCHAR2(200);

SELECT * FROM  tb_productos_pablo;

-- 2.1) Inserta 5 productos reales de ejemplo:
-- --- Todos con CODIGO_SKU único

-- --- 2 de TECNOLOGIA (uno con fecha de alta “01/09/2025”)
-- --- 2 de TECNOLOGIA (uno con fecha de alta “01/09/2025”)
INSERT INTO tb_productos_pablo (comercial_name, category, price, stock, fecha_alta, web_status, codigo_sku, inserted_by, tax)
VALUES ('Smartphone XYZ', 'tecnologia', 599.99, 50, TO_DATE('2025-09-01', 'YYYY-MM-DD'), 'activo', 'TEC001', USER, 0.21);

SELECT * FROM  tb_productos_pablo;

INSERT INTO tb_productos_pablo (comercial_name, category, price, stock, fecha_alta, web_status, codigo_sku, inserted_by, tax)
VALUES ('Auriculares Bluetooth', 'tecnologia', 89.50, 120, SYSDATE, 'activo', 'TEC002', USER, 0.21);

SELECT * FROM  tb_productos_pablo;

-- --- 2 de HOGAR (uno con stock = 0)
INSERT INTO tb_productos_pablo (comercial_name, category, price, stock, fecha_alta, web_status, codigo_sku, inserted_by, tax)
VALUES ('Aspiradora Robot', 'hogar', 299.99, 10, SYSDATE, 'activo', 'HOG001', USER, 0.21);

SELECT * FROM  tb_productos_pablo;

INSERT INTO tb_productos_pablo (comercial_name, category, price, stock, fecha_alta, web_status, codigo_sku, inserted_by, tax)
VALUES ('Lámpara de Mesa', 'hogar', 45.00, 0, SYSDATE, 'activo', 'HOG002', USER, 0.21);

SELECT * FROM  tb_productos_pablo;

-- --- 1 de DEPORTE con precio 0 y estado INACTIVO
INSERT INTO tb_productos_pablo (comercial_name, category, price, stock, fecha_alta, web_status, codigo_sku, inserted_by, tax)
VALUES ('Balón de Fútbol', 'deporte', 0, 0, SYSDATE, 'inactivo', 'DEP001', USER, 0.21);

SELECT * FROM  tb_productos_pablo;

-- 3.1) Incrementar el precio un 5% a los productos de TECNOLOGIA

UPDATE tb_productos_pablo
SET price = price * 1.05
WHERE category = 'tecnologia';

SELECT * FROM  tb_productos_pablo;
--3.2) Marcar como INACTIVO los productos con stock = 0

UPDATE tb_productos_pablo
SET web_status = 'inactivo'
WHERE stock = 0;

SELECT * FROM  tb_productos_pablo;

--3.6) Normalizar todas las fechas de alta al primer día del mes.

UPDATE tb_productos_pablo
SET fecha_alta = TRUNC(fecha_alta, 'MM')
WHERE fecha_alta != TRUNC(fecha_alta, 'MM');

SELECT * FROM  tb_productos_pablo;

--4) Eliminar de la tabla los productos INACTIVO con stock = 0 (no visibles y sin rotación).

DELETE FROM tb_productos_pablo
WHERE stock = 0 AND web_status = 'inactivo';

SELECT * FROM  tb_productos_pablo;

--6) Top 3 productos por precio (descendente).

SELECT * FROM tb_productos_pablo 
ORDER BY price DESC
FETCH FIRST 3 ROWS ONLY;

SELECT * FROM  tb_productos_pablo;